SELECT * FROM Person;
SELECT * FROM Bank;
SELECT * FROM Employee;
SELECT * FROM Banker;
SELECT * FROM Account;
SELECT * FROM Credit_cards;
SELECT * FROM Transaction;
SELECT * FROM Account_of;
SELECT * FROM Account_manager;